language: objective-c
osx_image: xcode8.2
rvm:
- 2.2

before_install:
- chmod a+x ./scripts/*.sh

install:
- ./scripts/install-unity.sh

script:
- ./scripts/build.sh PowerPrefs && ./scripts/run-tests.sh PowerPrefs

after_success:
- ./scripts/export-package.sh PowerPrefs
